// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzrAXENoeNQ83RxGa5Iz5qrkS1b4xCB1g',
    appId: '1:671698914020:web:7f1f6b6618517276cf3af1',
    messagingSenderId: '671698914020',
    projectId: 'donation-app-1a34c',
    authDomain: 'donation-app-1a34c.firebaseapp.com',
    storageBucket: 'donation-app-1a34c.appspot.com',
    measurementId: 'G-Z6GKR7LNZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy2A5WvbU6eg82dtF8weSG-F5nl_wTv4U',
    appId: '1:671698914020:android:29f5a57f258a5564cf3af1',
    messagingSenderId: '671698914020',
    projectId: 'donation-app-1a34c',
    storageBucket: 'donation-app-1a34c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMOe9BgALOs_Ivf02mZt5BosiVcpHrj38',
    appId: '1:671698914020:ios:871d9c2ceb4c2f37cf3af1',
    messagingSenderId: '671698914020',
    projectId: 'donation-app-1a34c',
    storageBucket: 'donation-app-1a34c.appspot.com',
    iosBundleId: 'com.example.donation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMOe9BgALOs_Ivf02mZt5BosiVcpHrj38',
    appId: '1:671698914020:ios:58c2f1d40d33e13dcf3af1',
    messagingSenderId: '671698914020',
    projectId: 'donation-app-1a34c',
    storageBucket: 'donation-app-1a34c.appspot.com',
    iosBundleId: 'com.example.donation.RunnerTests',
  );
}
